### PR TITLE
Drem MVP

### PR DESCRIPTION
**Pull request by Radilx**
TODO Before Merge: 

- [x] Screen sizing (when page is wide drem interface should stay in the center/small -- not stretch completely) (unclaimed)
- [x] Finish responsive layout (desktop) (unclaimed)
- [x] Need to integrate the own-profile view (right now it assumes it's someone else's profile (complete)
     - [x] Finish modal integration (edit profile modal)  ( in progress @Radilx )
     - [x] Modal should stay in fixed position even when scrolling (in progress @Radilx )
- [x] Currently, there are no visible routes when switching between views/screens (unclaimed)
- [x] Three dots context menu for posts should display buttons per Figma with a Popover (see PortfolioHeader.tsx on this branch for an example)
- [x] Add "Create a Post" Modal (@Radilx)
- [ ] Add Save Modal (SaveModal.tsx) (@axanthus) 
- [ ] Add Grow Modal (GrowModal.tsx) (@axanthus)
- [x] Add Deposit Modal (DepositModal.tsx) (@axanthus)
- [x] Add Swap Modal (SwapCopyTrade.tsx) (@Radilx)
- [x] Add dropdown to Create a Post Modal (@Radilx)
- [x] Copy trade button (desktop alignment & mobile spacing) (@Radilx)
- [ ] Refactor routes in pages folder based on next.js routes (@axanthus)
- [ ] add layout component for pages.

Nice to have (these may end up in a separate pull request):

- [ ] Graph is too large on smaller window sizes (desktop); it's impractical to have to scroll past it every time (@Radilx )
- [ ] Some modals are larger than others
- [ ] Styling and tailwind improvements for Add Strategies popover
- [ ] Refactor all Modal components (@axanthus)

### CODE REVIEW

**Comment by Radilx** [comment]
TODO:

- Screen sizing (when page is wide drem interface should stay in the center/small -- not stretch completely)
- Finish modal integration
- Finish responsive layout (desktop)
- Functionality

**Comment by lpolt** [comment]
Just a heads up, PR 100 involves refactoring older files, there may be merge conflicts when this needs to be reviewed

**Comment by axanthus** [comment]
Currently, there are no visible routes when switching between views/screens.

**Comment by Radilx** [comment]
- Created robust modal system based on React Context

**Comment by Radilx** [comment]
- Fixed alignment on Copy Trade posts

**Comment by Radilx** [comment]
@aalaoui12 Added recent trades/add strategy Popover: 

image

**Comment by Radilx** [comment]
- Added a section for "nice to have" improvements that will likely be in the next pull request

**Comment by axanthus** [comment]
@Radilx  and I are currently refactoring Modal components. I added a new ui folder with modal components underneath, and will continue to fine tune modal sizing and elements.

**Comment by Radilx** [comment]
TODO: Look into file refactor merge conflicts

**Review by lpolt — APPROVED** [review]
Lgtm

**Pull request merged**
