### PR TITLE
Feature/Reusable Button

### PR DESCRIPTION
**Pull request by Radilx**
## Summary:

In this diff, we add the "Reusable Button" component (Issue #46), per the spec in the [Figma](https://www.figma.com/file/VKVQRAFTJIfIw6vc6kD18I/Drem-MVP?node-id=419%3A4817). `ReusableButton.tsx` was created to close this task.  

---

## Test Plan:

```JavaScript
/* client/drem-interface/pages/index.tsx */ 

import type { NextPage } from "next";
import DremButton from "../components/DremButton";

const Home: NextPage = () => {
    return (
        <div>
            <DremButton primaryText={'Approve'} secondaryText={'Deny'}/>
        </div>
    );
};

export default Home;
```

**Screenshots:**

image 

image

image

---

### CODE REVIEW

**Comment by Radilx** [comment]
Let me know if you think there are any use cases that seem to be missing!

**Review by PatrickStarLee — CHANGES_REQUESTED** [review]
Everything looks good to me. I would suggest adding a bit of space between the two buttons, just like in the Figma (like when you're making the approve and deny buttons).

**Comment by Radilx** [comment]
Great point! I added a spacing property 👍

**Review by PatrickStarLee — APPROVED** [review]
Lgtm!

**Comment by Radilx** [comment]
Just to summarize our conversation in the Discord, originally we were passing in `spacing` as a number; however, tailwind looks for full class strings, such as `space-x-32`, in the file to decide whether to pull the CSS for that class name. `DremButton.tsx` only had `space-x-${spacing}`, which Tailwind's regex didn't catch, and thus the spacing CSS was not being bundled. There were many ways to fix this. Simply adding `space-x-0` to another element on the page, or making use of [safelists](https://tailwindcss.com/docs/content-configuration#safelisting-classes) would have worked.

For a quick fix, I decided to pass in the style itself, rather than the amount of spacing. This makes more sense from a design perspective anyway (since you can't pass in arbitrary numbers in the first place). I will review the codebase for similar bugs in a separate issue.

**Pull request merged**
