### PR TITLE
project improvements

### PR DESCRIPTION
**Pull request by axanthus**

### CODE REVIEW

**Comment by lpolt** [comment]
Runtime error on my machine

Screenshot 2023-04-08 095315

**Comment by axanthus** [comment]
Was this on startup? Did you run npm install first? I didn't encounter that error

**Review by lpolt — APPROVED** [review]
lgtm. Before merging, we'll need to fix the above error. if unfeasible here start a new pr for it

**Comment by axanthus** [comment]
Error was fixed. .env problem on @lpolt's end

**Pull request merged**
