### PR TITLE
Feature/reusable card component

### PR DESCRIPTION
**Pull request by jodychui**

### CODE REVIEW

**Review by Evan-Nishi — COMMENTED** [review]
Remove the nested div that the children are in as it may make styling slightly more annoying later.

**Comment by Evan-Nishi** [comment]
Also we should talk to the team about renaming components as this should really be named Card, and the current Card.tsx should be built incorporating this element as the name is rather long.

**Comment by PatrickStarLee** [comment]
What's with the current Card.tsx file?

**Review by Evan-Nishi — APPROVED** [review]
Looks good.  Thanks for bearing with me on the jsdoc guidlines.

**Pull request merged**
