### PR TITLE
User Post With Replies Component

### PR DESCRIPTION
**Pull request by Radilx**
## Summary 

In this diff, we add the User Post With Replies component (Issue #51), per the spec in the [Figma](https://www.figma.com/file/VKVQRAFTJIfIw6vc6kD18I/Drem-MVP?node-id=419%3A4817). `UserPost.tsx` and `TradePost.tsx` were modified to be responsive and support replies.

---

## Test Plan:

- Usage is as follows:

```JavaScript
            <TradePost
                name={"Darius Johnson"}
                username={"$dariusjohnson"}
                profpic={require("/public/pfp-small.png")}
                text={
                    "Lorem ipsum."
                }
                replies={[
                    {
                        name:"Darius Johnson",
                        username: "$dariusjohnson",
                        profpic: require("/public/pfp-small.png"),
                        text: "Lorem ipsum."
                    },
                    ...
                ]}
            />
```

- Screenshots:

| Mobile | Desktop |
| --- | --- |
| image  |  image |

### CODE REVIEW

**Comment by Radilx** [comment]
QQ for @Eric-Hong99: 

I noticed when testing this in the `vertical-slice` page that the component looks off because all of the Tailwind breakpoints are based on media queries (the size of the entire page), but the post itself is inside a much smaller div. 

I found [this fairly long discussion](https://github.com/tailwindlabs/tailwindcss/issues/1563) in the Tailwind Issues page, which eventually led to the creation of [this library](https://github.com/dgknca/tailwindcss-container-query) which lets you base the styling off of the size of the parent container instead of the size of the entire page. It seems like it's designed for situations like this where the component could be used anywhere.

Let me know if this is overkill or there is another way you'd like to see this addressed. Not a Tailwind expert :)

**Review by Evan-Nishi — COMMENTED** [review]
Please use the hex values in the tailwind config instead of arbitrary hex as it makes it easier when we choose to have a light/dark mode.

**Comment by Radilx** [comment]
Thank you for the feedback @Evan-Nishi. I just switched to using the tailwind config.

**Review by Evan-Nishi — APPROVED** [review]
Good work.  Thanks for making the changes.

**Pull request merged**
