### PR TITLE
Feature/user comment

### PR DESCRIPTION
**Pull request by PatrickStarLee**

### CODE REVIEW

**Comment by Eric-Hong99** [comment]
Not sure if this was discussed before but wondering why a class React component was chosen over a functional component

**Comment by Eric-Hong99** [comment]
Looks good from my end, do you want to talk about dynamic props/variables for likes/dislikes + comment numbers?

**Comment by PatrickStarLee** [comment]
Sure. I do know a bit about states via React Hooks, but we can discuss.

**Comment by Eric-Hong99** [comment]
Add in timeCreated prop + use it to display time since post was created in component

**Review by lpolt — APPROVED** [review]
lgtm

**Pull request merged**
