### PR TITLE
Refactoring frontend file structure

### PR DESCRIPTION
**Pull request by Evan-Nishi**
Changes made:
* Removed redundant drem-interface/client directory
* Grouped certain components by feature (should discuss with group later), general components still in /components folder
* Removed unused dummy component folders Component1 and Component2
* Squashed component TradeList and TradListItem into one file

TODO:
* Get feedback on component grouping
* Fix merge conflicts

### CODE REVIEW

**Comment by Radilx** [comment]
There's `client/screens` as well as `client/components/screens`. Would it be okay to merge these?

**Comment by Evan-Nishi** [comment]
Oh I didn't catch that.  That would definitely be wise.

**Comment by Evan-Nishi** [comment]
Here is a brief writeup on the new filesystem changes.

After experimenting with a few different ways to organize components, I think it would be wise to organize components based on features.  General components will still be in the root /components directory, while components specific to a feature (ie profile) will go in the own folder.  This is just to reduce clutter and to prevent the creation of redundant components.  

I haven't worked on many of the components here so I might need help organizing the rest of the components into feature specific folders.  I tested the changes, and there weren't any import errors on my end.

Other than that, I just squashed the folder /drem-interface/client, into /client and made merged the two /screens folder so that now there is only one in the /client directory.   

Feedback would be greatly appreciated.

**Comment by Evan-Nishi** [comment]
I resolved the present merge conflicts.  I would like to have another team member to look over it though, as although I did my best to test it, things still may break.  Please pull asap.

**Comment by axanthus** [comment]
I just ran the app, found some broken imports in _app.tsx and for portfolio screen, and fixed them.

**Review by axanthus — APPROVED** [review]
app works on my end.

**Comment by Evan-Nishi** [comment]
Good catch, looks like I forgot to stage those changes on my machine.

**Pull request merged**
