### PR TITLE
modify menu component

### PR DESCRIPTION
**Pull request by jonathanfong098**
NOTE: If this pull request is approved then other developers must run "npm install @headlessui/react" 
<Popover> Documentation: https://headlessui.com/react/popover
<Transition> Documentation: https://headlessui.com/react/transition
1. Created menu component based on the Headless UI popover component. The menu component contains buttons for navigating through the menu to submenus and buttons to complete certain actions
2. Created the "Create" button in the navigation bar since the menu component uses the <Popover> component from Headless UI which requires developers to add a <Popover.button> that will open and close the popover. 
3. Added a <Transition> to the menu so that it will enter the page smoothly. 
Headless UI Documentation:
4.Added images to the /public/images folder which are used as button icons

### CODE REVIEW

**Comment by Evan-Nishi** [comment]
We should discuss with the team before adding more libraries.  The library proposed would add bulk and would render much of our already in house built components redundant but would make things a lot faster.

**Comment by lpolt** [comment]
This pr has conflicts that need to be resolved too. Reach out to me about this when you get the chance

**Comment by jonathanfong098** [comment]
I believe I resolved the merge conflicts so this pull request can undergo review.

**Comment by Radilx** [comment]
image

Looks good to me, great work! The new library has been approved. I am going to close this and merge separately though since the merge conflicts here would take a while to resolve (this version of the repo is > 2 months old). Will open a separate PR in a moment.

**Comment by Radilx** [comment]
Changes merged into `feature/navbar`.

**Pull request closed without merging**
