### PR TITLE
Feature/recent-trade

### PR DESCRIPTION
**Pull request by Radilx**
## Summary:

In this diff, we add the "Recent Trade Item" component (Issue #21), per the spec in the [Figma](https://www.figma.com/file/VKVQRAFTJIfIw6vc6kD18I/Drem-MVP?node-id=419%3A4817). `RecentTrade.tsx` was created to close this task.  

---

## Test Plan:

```JavaScript
/* client/drem-interface/pages/index.tsx */ 

import type { NextPage } from "next";
import RecentTrade from "../components/RecentTrade";

const Home: NextPage = () => {
    return (
        <div>
            <RecentTrade timestamp={new Date()} from={'$ETH'} to={'$LUNA'}/>
        </div>
    );
};

export default Home;
```

| Screenshot |
| --- |
| image |

---

## Caveats 

- Waiting on exact date formatting until we have more information about props 

- Now that the "Copy Trade" button is being used in multiple screens, it should be its own component. I am working on a separate issue for this #66

### CODE REVIEW

**Review by PatrickStarLee — CHANGES_REQUESTED** [review]
image

The trade card looks good so far. I think you could adjust the text size for the time stamp and trade text to be 1-2 lines just so it looks nice on all screen breakpoints. Also, make sure to include the border for this trade card like in the Figma. You can use the Card.tsx component to include the border.

**Comment by Radilx** [comment]
Good catch, I didn't notice the border! As for the text size, I think it depends less on the screen breakpoint, and more on the size of the parent container, which I'm not sure of. I did discuss this a bit in #52, do you have any ideas?

**Comment by PatrickStarLee** [comment]
image

If we're using a parent container as a baseline for how big the trade card could be, then this entire middle section of the website would be the parent and the other smaller components in that section are the children. I might have to look more into this if I have time. I'm not sure if that answers your question.

Here's my follow-up question: When you said "the component could be used anywhere," are you referring to the different screen sizes or different pages of the application?

**Comment by PatrickStarLee** [comment]
Actually, now that I mentioned about the parent, I do think it makes sense that the trade card and other smaller components will depend on the parent (the middle div) because the size of the div will depend on the size of the user's screen. It would also save us time to individually find the breakpoints for each of the smaller components. Thoughts?

**Comment by Radilx** [comment]
- Fixed merge conflicts

**Review by lpolt — APPROVED** [review]
lgtm

**Pull request closed without merging**
